// <auto-generated />
using DemoApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoApp.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20230810143452_CreateRankenEmpsDB")]
    partial class CreateRankenEmpsDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DemoApp.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeID = 1,
                            DeptName = "AWD",
                            FirstName = "Jeff",
                            LastName = "Scott",
                            Salary = 34567.00m
                        },
                        new
                        {
                            EmployeeID = 2,
                            DeptName = "AWD",
                            FirstName = "Evan",
                            LastName = "Gudmestad",
                            Salary = 78901.00m
                        },
                        new
                        {
                            EmployeeID = 3,
                            DeptName = "IT",
                            FirstName = "Tom",
                            LastName = "Anderson",
                            Salary = 56789.00m
                        },
                        new
                        {
                            EmployeeID = 4,
                            DeptName = "IT",
                            FirstName = "Ashley",
                            LastName = "Reddick",
                            Salary = 77777.00m
                        },
                        new
                        {
                            EmployeeID = 5,
                            DeptName = "ADM",
                            FirstName = "Charles",
                            LastName = "Corrigan",
                            Salary = 98765.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
